---
- name: Install vim, wget, and apache
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - vim
    - wget
    - httpd
    - httpd-tools
    - htop

# Configure apache
- name: Ensure httpd is running
  service:
    name: httpd 
    state: started

# Deploy apache hello world app
- name: Create install directory
  file:
    state: directory
    path: /var/www/html
    owner: apache
    group: apache
    mode: 0755

- name: Copy files to remote host
  copy:
    src: files/demoapp
    dest: /var/www/html
    owner: apache
    group: apache
    mode: 0755
